### ISSUE TITLE
Short-cut for "Next replay move"

### ISSUE THREAD

**Issue by simfann** [b0n541/jskat-multimodule#136]
It's very long-winded to show the moves of a replayed game, because you always have to do 2 menu steps for that. I suggest, to introduce at least for menu points "Skat table - Next replay move" a keyboard short-cut, so that you can go faster through the replayed moves.

**Comment by b0n541** [comment]
Hmm, there are those buttons already in the toolbar:

![Screenshot from 2022-01-22 12-49-32](https://user-images.githubusercontent.com/2326303/150637379-38ed8f46-647f-486c-8930-64dabcfe8d31.png)

Have you deactivated the toolbar in the settings? Or isn't it visible at all. Maybe a problem of mixing Java Swing and JavaFX together in one UI.

**Comment by simfann** [comment]
The toolbar is also a problem for me, because it doesn't work on my computer correctly. But it's true, I had deactivated the toolbar for that reason and had forgot about that fact.

**Comment by simfann** [comment]
Because toolbar is sufficient, I close this issue.
