### ISSUE TITLE
Ramsch

### ISSUE THREAD

**Issue by peter149** [b0n541/jskat-multimodule#143]
Die Ramschpunkte werden in der Spiellist angezeigt, aber dem jeweiligen Spieler nicht zugeordnet.
![Spielliste-spiel2 Ramsch](https://user-images.githubusercontent.com/19823540/180496762-46a67ebd-8d8e-43c4-b149-3abc84aef83f.jpg)

**Comment by b0n541** [comment]
Viele Dank für diese Fehlermeldung. Ich kann das Problem nachvollziehen.
---
Many thanks for reporting this bug. I can reproduce it.

**Comment by b0n541** [comment]
Der Fehler ist in Version 0.21.0 behoben.

The bug is fixed in version 0.21.0.
