### ISSUE TITLE
Graphic Issue: Card visibility

### ISSUE THREAD

**Issue by hhenn** [b0n541/jskat-multimodule#31]
The cards are not spread, as you can see in the screenshot.
I can view all the cards by hovering over them, but it really sucks.

My system is: Mac OS X 10.10.2 with Java 1.7:
java version "1.7.0_21"
Java(TM) SE Runtime Environment (build 1.7.0_21-b12)
Java HotSpot(TM) 64-Bit Server VM (build 23.21-b01, mixed mode)

![screen shot 2015-02-14 at 15 47 34](https://cloud.githubusercontent.com/assets/6004381/6199957/3955a49e-b461-11e4-946e-f7da37350c72.png)

**Comment by b0n541** [comment]
Unfortunately I haven't tested JSkat with Mac OS because I have no Mac available a.t.m.. You could try to minimize/maximize the window. Maybe the layout is done again and the issue will be fixed. Apart from that I will try to find a Mac to test it for my own.

**Comment by b0n541** [comment]
I finally was able to track down the bug. It is fixed now in bugfix version v 0.14.3.
