### ISSUE TITLE
Add an editor config with basic formatting rules

### ISSUE THREAD

**Issue by mlrdev** [b0n541/jskat-multimodule#49]
Even though it is limited, this will provide very equal formatting regardless of the used IDE within this project at literally no cost. See: http://editorconfig.org/#overview

There's no need to import (project-specific) settings as long as the IDE supports (e.g. via plugin) editor configs, which is very likely for every common IDE nowadays.

**Comment by b0n541** [comment]
+1 from my side. We could do it. I would like to use a common code style / formatting rules. Either the original Java code style or the one from Google.

**Comment by mlrdev** [comment]
Maybe this was way too enthusiastic, since the editorconfig does not support as much as I thought.
May you could close this question/ticket.

**Comment by b0n541** [comment]
Ok, let's use the standard Eclipse formatter then.
