### ISSUE TITLE
AI player plays Schwarz during first round: Skat table hangs

### ISSUE THREAD

**Issue by tobbi** [b0n541/jskat-multimodule#52]
It happens ever so often, when an AI player plays schwarz during the first round, the skat table hangs and I cannot do a new game. I have to close the skat table and create a new one if that is the case. The hang only happens if an AI player plays Schwarz during the first round and doesn't happen if it plays Schwarz in any subsequent rounds.

**Comment by b0n541** [comment]
This was a really nasty bug. It is fixed in the code for the next release. I'll release 0.16 shortly because of this annoying bug.
