### ISSUE TITLE
Error Debian and Version 0.16.0

### ISSUE THREAD

**Issue by lugau45** [b0n541/jskat-multimodule#56]
Fehler: Hauptklasse org.jskat.JSkatFX konnte nicht gefunden oder geladen werden
System Debian 9

Please create an .deb Package

**Comment by b0n541** [comment]
Unfortunately I have only Ubuntu to test JSkat under Linux. Starting JSkat with

`java -jar JSkat-0.16.0-all.jar`

in a terminal works. Double clicking on the JAR files works too but the GUI doesn't show any widgets.

How did you start JSkat under Debian 9?

**Comment by lugau45** [comment]
Not work:
java -jar JSkat.jar
Fehler: Hauptklasse org.jskat.JSkatFX konnte nicht gefunden oder geladen 
werden

In Terminal

Am Montag, 25. September 2017, 14:41:54 CEST schrieb Jan Schäfer:
> Unfortunately I have only Ubuntu to test JSkat under Linux. Starting JSkat
> with
> 
> `java -jar JSkat-0.16.0-all.jar`
> 
> in a terminal works. Double clicking on the JAR files works too but the GUI
> doesn't show any widgets.
> 
> How did you start JSkat under Debian 9?


-- 
Webseite www.familie-haenisch.de
Telefon 03532251788
Fax 03532251768

**Comment by b0n541** [comment]
O.k., I think I might have a glue, what's causing this:

Are you using OpenJDK instead of Oracle's JDK?

If yes, you need to install the package "openjfx" too. I tried it under Ubuntu and without "openjfx" I got the same error as mentioned above. After installing "openjfx" the GUI opened.

**Comment by lugau45** [comment]
very good support, that was the solution.
openjfx

thank you
Am Montag, 25. September 2017, 15:41:03 CEST schrieb Jan Schäfer:
> O.k., I think I might have a glue, what's causing this:
> 
> Are you using OpenJDK instead of Oracle's JDK?
> 
> If yes, you need to install the package "openjfx" too. I tried it under
> Ubuntu and without "openjfx" I got the same error as mentioned above. After
> installing "openjfx" the GUI opened.


-- 
Webseite www.familie-haenisch.de
Telefon 03532251788
Fax 03532251768

**Comment by lugau45** [comment]
login on the server has no function, the server is offline

Am Montag, 25. September 2017, 15:41:03 CEST schrieb Jan Schäfer:
> O.k., I think I might have a glue, what's causing this:
> 
> Are you using OpenJDK instead of Oracle's JDK?
> 
> If yes, you need to install the package "openjfx" too. I tried it under
> Ubuntu and without "openjfx" I got the same error as mentioned above. After
> installing "openjfx" the GUI opened.


-- 
Webseite www.familie-haenisch.de
Telefon 03532251788
Fax 03532251768

**Comment by b0n541** [comment]
O.k., then I will update the documentation accordingly.

The server seems to be down at the moment. I'll try to contact the admin.

**Comment by lugau45** [comment]
at a local table I can't see any cards, in the terminal there is the following 
error: java -jar JSkat. jar 

(java: 21075): Gtk-WARNING **: In the module path "adwaita" no topic engine 
could be found, but the

(java: 21075): Gtk-WARNING **: In the module path "adwaita" no topic engine 
could be found, but the

Am Montag, 25. September 2017, 15:48:36 CEST schrieb Jan Schäfer:
> O.k., then I will update the documentation accordingly.
> 
> The server seems to be down at the moment. I'll try to contact the admin.
-- 
Webseite www.familie-haenisch.de
Telefon 03532251788
Fax 03532251768

**Comment by b0n541** [comment]
Hard to tell, what's going on here. Haven't found any hints by googling the error message.

**Comment by b0n541** [comment]
Would you please try to start an older version of JSkat (e.g. https://github.com/b0n541/jskat-multimodule/releases/tag/v0.15.0)?

**Comment by b0n541** [comment]
Btw. the skat server is up and running again.

**Comment by lugau45** [comment]
the 0.15.0 runs without problems

Am Montag, 25. September 2017, 09:38:00 CEST schrieb Jan Schäfer:
> Would you please try to start an older version of JSkat (e.g.
> https://github.com/b0n541/jskat-multimodule/releases/tag/v0.15.0)?
-- 
Webseite www.familie-haenisch.de
Telefon 03532251788
Fax 03532251768

**Comment by b0n541** [comment]
Maybe your issue is related to bad syncing of Swing and JavaFX components. We have added some fixes lately (#61).

Could you please try out the latest build from here: 

https://www.jskat.org/JSkat-0.17.0-SNAPSHOT-all.jar

**Comment by b0n541** [comment]
Since version 0.17 JSkat requires at least Java 11 and is shipped with JavaFX included. So this bug might not occur anymore.
