### ISSUE TITLE
Grand games against AI get aborted (version 0.16.0)

### ISSUE THREAD

**Issue by steadshot** [b0n541/jskat-multimodule#57]
Every time I play a Grand game against the AI and one of the opponents is forced to play the Jack of Clubs, I get an alert "Played schwarz // Player X played schwarz with card Unknown card." and see the game over screen (the game counts as a win), e.g. "Grand without 1 play 2 Hand Schneider Schwarz] - Won - 16 versus 104 Points". That player's hand indeed shows a lone Jack of Clubs.
I'm on version 0.16.0.

**Comment by b0n541** [comment]
Thanks for reporting that bug. I can reproduce the behaviour of that player with a unit test.

**Comment by b0n541** [comment]
Just released a new bugfix version 0.16.1 with the fix.
