### ISSUE TITLE
JSkat hangs when clicking Tools > Options

### ISSUE THREAD

**Issue by tobbi** [b0n541/jskat-multimodule#60]
I can't tell a lot about this issue. All I know is that the game hangs when I go to Tools > Options. 

I'm using the latest version of JSkat (0.16.1) and Java (10.0.2) on OS X 10.13.6

**Comment by b0n541** [comment]
Thanks for reporting this issue. Unfortunately I can't test JSkat under OS X myself.

Would you please try to run JSkat from the console with

```
java -jar JSkat-0.16.1-all.jar
```

and see if there are some error messages printed out?

And could you provide the JSkat log file from `<user-home>/.jskat/JSkat.log` as well?

**Comment by tobbi** [comment]
There are no error messages on the console (or any output for that matter). JSkat log attached:

[JSkat.log](https://github.com/b0n541/jskat-multimodule/files/2284382/JSkat.log)

I managed to get a stacktrace with jcmd.print (not sure if this is useful for you):
[jskat_thread.txt](https://github.com/b0n541/jskat-multimodule/files/2284384/jskat_thread.txt)

**Comment by b0n541** [comment]
I have fixed the broken look and feel and made it compatible with Java 10. A snapshot build is available under

https://www.jskat.org/JSkat-0.17.0-SNAPSHOT-all.jar

Please give it a try.

Another thing worth trying is to delete the `jskat.properties` file under `<user-home>/.jskat/`. Maybe there is a setting that could not be set in the options dialog during opening.

**Comment by tobbi** [comment]
Unfortunately, neither of those things helped. I might try setting up Eclipse and compiling jskat myself to see whether I can try to debug the issue.
