### ISSUE TITLE
Jar not starting

### ISSUE THREAD

**Issue by Jokah16** [b0n541/jskat-multimodule#63]
Hi,
I downloaded the jar to play, unfortunaly the jar will not open despite java 8 is installed, there is not implication why.
Thanks!

**Comment by b0n541** [comment]
I just tried it myself with Windows 10 and Java 8 Update 191 and JSkat is starting as expected. Do you have the latest Java version installed?

You can find out with this command:

`java -version`

**Comment by Jokah16** [comment]
I actually did not, but instead I had Java 8 Update 192 installed. Following your advice, I deinstalled Update 192 and installed 191, unfortunaly without a positive result. Weirdly, all my other .jar applications are running just fine, only JSkat does not even show any error or notification.

**Comment by b0n541** [comment]
Hmm, it's hard to guess what's going wrong without having any error message. I could think of some incompatibility with your graphics driver and JavaFX that I don't have in my virtualized Windows 10 here. 

You could try out whether the non-JavaFX version 0.15 of JSkat is running to prove that assumption:

https://github.com/b0n541/jskat-multimodule/releases/download/v0.15.0/JSkat-0.15.0.jar

I'm currently working on making JSkat compatible with Java 11. You can checkout the latest state from the develop branch and do 

`gradlew.bat run`

in the directory you've checked out.

**Comment by Jokah16** [comment]
The non-JavaFX version is working fine, so the problem seems to be my graphic driver. Thanks anyway!

**Comment by b0n541** [comment]
I have built a new snapshot JAR from develop with Java 11:

https://jskat.org/JSkat-Java11-Windows-0.17.0-SNAPSHOT.jar

So you could try to install Java 11 and give it a try with `java -jar`

**Comment by mlrdev** [comment]
Hi, I don't know whether the problem still exists for Jokah16.

I've tested the snapshot with a Win10 machine, java version "12.0.2" 2019-07-16, while starting it from a Git Bash and I was able to play on a local table.

---
There where just some warnings (ReflectionsExceptions), e.g.:

> could not get type for name org.codehaus.groovy.runtime.GeneratedClosure
> could not get type for name com.google.gson.JsonDeserializer

and the like.

**Comment by b0n541** [comment]
Since version 0.17 JSkat requires at least Java 11 and is shipped with JavaFX included. So this bug might not occur anymore.
