### ISSUE TITLE
Error: Could not find or load main class org.jskat.JSkatFX

### ISSUE THREAD

**Issue by shoultsy** [b0n541/jskat-multimodule#65]
When trying to open the JSkat-0.16.1-all.jar file on ubuntu linux it returns this error:
`Error: Could not find or load main class org.jskat.JSkatFX
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
`

**Comment by b0n541** [comment]
Thanks for reporting that issue.

Which Java version are you using?

To get that information please type into a terminal:

`java -version`

JSkat version 0.16.1 is compatible with JDK 8 from Oracle. I haven't tested all the other versions in between but I can say that I get the same error message as you posted with Open JDK 11.

We are currently preparing the next version of JSkat that is compatible with Java 11. You can try a snap shot build available from here:

[https://www.jskat.org/JSkat-Java11-Linux-0.17-0-SNAPSHOT.jar](https://www.jskat.org/JSkat-Java11-Linux-0.17-0-SNAPSHOT.jar)

**Comment by shoultsy** [comment]
I was using JDK 11. Problem fixed
