### ISSUE TITLE
Show the skat after the game

### ISSUE THREAD

**Issue by kasbah** [b0n541/jskat-multimodule#82]
Would be nice to be able to see what was in the Skat in the after game analysis.

**Comment by b0n541** [comment]
@kasbah I added the dealt skat cards to the after game analysis. Would you please test whether this suits your needs?

**Comment by kasbah** [comment]
Oh wow, thanks! I built the master branch and played a test game with zoot and theCount and it looks like it's working perfectly. This will help a lot with figuring whether a player was lucky with the Skat. 

I guess I didn't think of it before but in a real game you don't see the Skat but you can actually see what the player put away ("was der Spieler gedrückt hat") when tallying the score, which you still have to figure out by elimination in JSKat, even if you can now see the Skat.

**Comment by b0n541** [comment]
You're right this makes more sense. I even thought of showing both the dealt skat and the discarded one. But there is not enough space at the moment to show both properly.

I hope the current state is sufficient for you?

**Comment by kasbah** [comment]
Yes, I tested it again. Looks great! Thanks!
