### ISSUE TITLE
Java version for jSkat for Windows 10 32-bit

### ISSUE THREAD

**Issue by stone12683** [b0n541/jskat-multimodule#98]
Hello,

I have successfully installed the Skat game JSkat-0.19.0-windows with the Java software jdk-11.0.10 on a Windows 10 64-bit system. The game runs flawlessly.

Which Java version do I have to use for the installation on a Windows 10 32-bit system? The version jdk-11.0.10 is only available for 64-bit systems.

Unfortunately, it didn't work with these versions:
jre1.8.0_281 and
jdk1.8.0_261

Please send a link to download the correct Java version.

Help!

Thanks from Berlin
stone12683

**Comment by b0n541** [comment]
JSkat needs at least Java 11 to run. We always stick to the LTS version of Java to have a good balance between using new features of Java and having most user systems supported.
Unfortunately Oracle seems to no longer support 32 bit systems with Java 11.
But you could give Adopt Open JDK a try: https://adoptopenjdk.net/releases.html

**Comment by stone12683** [comment]
Hallo Jan,

danke für die schnelle Antwort. Ja, hab's probiert, funzt leider nicht :-(.
So what.

nice weekend
stone

**Comment by b0n541** [comment]
Supporting 32 bit systems seems to be too much effort or even not possible with JavaFX.
